/* Generated by house-palette from palette.json — do not edit by hand.
   Source revision fixture, sha256 a61d839291aa390dd3c17a6533632c660ba0cd580af1d64a7007e5562ef73ca0.
   Regenerate with bin/render --target tinshell-tokens-ts; a hand edit fails bin/render --check. */

/**
 * Palette constants for the shell tree, as JS.
 *
 * The stylesheet carries every one of these as an `--tinshell-*` custom
 * property, and a CSS consumer reads it there. This module exists for the
 * consumers CSS cannot reach: a Cairo painter, a `Pango.FontDescription`, or a
 * config fallback that is a JS value before it is ever CSS text.
 *
 * Palette values only — a token's non-colour companions (the font stack, the
 * radii, the row padding) stay in the shell's own module.
 */

/** Primary text ink. CSS carrier: `--tinshell-ink`. */
export const INK = "#e6e6e6"

/** Emphasis ink: the brightest tier, for a glyph or a one-word label. CSS carrier: `--tinshell-ink-emphasis`. */
export const INK_EMPHASIS = "#ffffff"

/** Secondary text ink — timestamps, hints. CSS carrier: `--tinshell-ink-secondary`. */
export const INK_SECONDARY = "#c9c9c9"

/** De-emphasised ink. CSS carrier: `--tinshell-ink-muted`. */
export const INK_MUTED = "#a6a6a6"

/** Faint ink, alpha carried. CSS carrier: `--tinshell-ink-faint`. */
export const INK_FAINT = "rgba(166, 166, 166, 0.55)"

/** The suite accent — caret, focus/active control, the active path segment. CSS carrier: `--tinshell-accent`. */
export const ACCENT = "#8ab5f7"

/** The lighter accent step, for a name that must read as related to the accent. CSS carrier: `--tinshell-accent-soft`. */
export const ACCENT_SOFT = "#adcbf9"

/** The frosted panel base at the shell's own alpha. CSS carrier: `--tinshell-panel`. */
export const PANEL = "rgba(10, 12, 17, 0.5)"

/** The wash painted inside the panel. CSS carrier: `--tinshell-wash`. */
export const WASH = "rgba(255, 255, 255, 0.1)"

/** The selected row's fill. CSS carrier: `--tinshell-row-selected`. */
export const ROW_SELECTED = "rgba(10, 12, 17, 0.72)"

/** The hairline separating blocks on the panel. CSS carrier: `--tinshell-hairline`. */
export const HAIRLINE = "rgba(255, 255, 255, 0.06)"

/** State colours. CSS carriers: `--tinshell-error`, `--tinshell-warning`, `--tinshell-success`. */
export const ERROR = "#ff6b6b"
export const WARNING = "#f0b35a"
export const SUCCESS = "#8af7ae"

/** The scrollbar pill's three states. CSS carriers: `--tinshell-scrollbar-thumb*`. */
export const SCROLLBAR_THUMB = "rgba(255, 255, 255, 0.22)"
export const SCROLLBAR_THUMB_HOVER = "rgba(255, 255, 255, 0.3)"
export const SCROLLBAR_THUMB_ACTIVE = "rgba(255, 255, 255, 0.45)"
