-- Generated by house-palette from palette.json — do not edit by hand.
-- Source revision fixture, sha256 a61d839291aa390dd3c17a6533632c660ba0cd580af1d64a7007e5562ef73ca0.
-- Regenerate with bin/render --target hypr-palette; a hand edit fails bin/render --check.

-- Palette table for Hyprland's Lua config, read with `local palette = require("palette")`.
-- Colours are Hyprland's own rgba(rrggbbaa) form: alpha 255 for a solid role,
-- the role's alpha where it carries one.

return {
    -- Surfaces
    panel_base = "rgba(0a0c11ff)",
    view_base = "rgba(16181cff)",
    window_base = "rgba(1b1d22ff)",
    surface_raised = "rgba(23262cff)",
    keyboard_panel_base = "rgba(171a21ff)",

    -- Ink
    ink_on_accent = "rgba(14171cff)",
    ink_emphasis = "rgba(ffffffff)",
    ink = "rgba(e6e6e6ff)",
    ink_secondary = "rgba(c9c9c9ff)",
    ink_muted = "rgba(a6a6a6ff)",
    ink_faint = "rgba(a6a6a68c)",
    ink_faint_solid = "rgba(606163ff)",

    -- Accent family
    accent = "rgba(8ab5f7ff)",
    accent_soft = "rgba(adcbf9ff)",
    accent_cyan = "rgba(4cccf2ff)",
    accent_violet = "rgba(b88cf2ff)",

    -- State
    error = "rgba(ff6b6bff)",
    warning = "rgba(f0b35aff)",
    success = "rgba(8af7aeff)",

    -- Window borders
    border_active = "rgba(ccccccff)",
    border_inactive = "rgba(00000000)",

    -- Hairlines, washes and interaction fills
    hairline = "rgba(ffffff0f)",
    border_strong = "rgba(ffffff1a)",
    hover = "rgba(ffffff14)",
    hover_strong = "rgba(ffffff24)",
    wash = "rgba(ffffff1a)",
    card_wash = "rgba(ffffff0d)",
    selection_menu = "rgba(8ab5f738)",
    selection_row = "rgba(8ab5f759)",
    selection_note = "rgba(8ab5f773)",
    accent_fill = "rgba(8ab5f72e)",
    focus_ring = "rgba(8ab5f78c)",
    danger_fill = "rgba(ff6b6b29)",
    row_highlight = "rgba(ffffff1a)",
    row_active = "rgba(ffffff29)",
    row_selected = "rgba(0a0c11b8)",
    text_shadow = "rgba(00000070)",
}
