/**
 * The committed goldens are a rendered fixture tree. A change to the source or
 * to a template shows up here as a diff of the generated bytes, which is the
 * point: the output is reviewed like any other source in this repository.
 *
 * Regenerate after an intended change with:
 *   HOUSE_PALETTE_REVISION=fixture bin/render --out tests/golden --tinshell tests/golden/tinshell
 */

import assert from "node:assert/strict"
import { readdirSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { test } from "node:test"
import { repoRoot } from "../src/render.ts"
import { renderInMemory } from "./fixture.ts"

const GOLDEN = join(repoRoot, "tests", "golden")

test("every rendered file matches its golden byte for byte", () => {
  const files = renderInMemory().map((file) => ({ ...file, goldenPath: join(GOLDEN, file.path.replace(/^\/fixture\/?/, "")) }))
  assert.ok(files.length >= 15, `only ${files.length} files rendered`)
  for (const file of files) {
    const golden = readFileSync(file.goldenPath, "utf8")
    assert.equal(file.content, golden, `${file.target} differs from ${file.goldenPath}`)
  }
})

test("the golden tree holds no extra file", () => {
  const rendered = new Set(renderInMemory().map((file) => file.path.replace(/^\/fixture\/?/, "")))
  const walk = (relative: string, found: string[] = []): string[] => {
    for (const entry of readdirSync(join(GOLDEN, relative), { withFileTypes: true })) {
      const next = join(relative, entry.name)
      if (entry.isDirectory()) walk(next, found)
      else found.push(next)
    }
    return found
  }
  for (const file of walk("")) {
    assert.ok(rendered.has(file), `${file} is in the golden tree and no longer rendered`)
  }
})
