/**
 * The templates and the target registry are one list: a template no target
 * renders is dead weight, a target with no template is a broken render, and no
 * template may leave a placeholder behind.
 */

import assert from "node:assert/strict"
import { readdirSync } from "node:fs"
import { join } from "node:path"
import { test } from "node:test"
import { repoRoot } from "../src/render.ts"
import { applySteps, heldBackTargets, targets } from "../src/targets.ts"
import { renderInMemory } from "./fixture.ts"

test("every template is rendered by exactly one target", () => {
  const declared = targets.map((target) => target.template).sort()
  assert.equal(new Set(declared).size, declared.length, "two targets share a template")
  const onDisk = readdirSync(join(repoRoot, "templates")).sort()
  assert.deepEqual(onDisk, declared, "templates/ and the target registry disagree")
})

test("no target renders with an unresolved placeholder", () => {
  for (const file of renderInMemory()) {
    assert.ok(!file.content.includes("{{"), `${file.target}: ${file.content.match(/\{\{[^}]*\}\}/)?.[0]}`)
    assert.ok(!/undefined|NaN/.test(file.content), `${file.target}: rendered an undefined value`)
  }
})

test("every generated file that can carry a header carries one naming its source and its command", () => {
  for (const file of renderInMemory()) {
    const target = targets.find((entry) => entry.name === file.target)
    if (target === undefined) continue // the manifest is JSON and carries its provenance in its own fields
    if (target.header === "none") {
      assert.ok(!file.content.startsWith("/*"), `${file.target}: JSON must not carry a comment header`)
      continue
    }
    const head = file.content.split("\n", 3).join("\n")
    assert.match(head, /Generated by house-palette from palette\.json/)
    assert.match(head, /sha256 [0-9a-f]{64}/)
    assert.match(head, new RegExp(`bin/render --target ${target.name}`))
  }
})

test("a target whose destination is not loaded natively records the apply step it waits for", () => {
  for (const target of targets.filter((entry) => entry.mechanism.startsWith("none:"))) {
    const steps = applySteps.filter((step) => step.name.startsWith(target.name.split("-")[0] as string))
    assert.ok(steps.length > 0, `${target.name} has no apply step recorded`)
  }
})

test("every held-back target says why", () => {
  for (const entry of heldBackTargets) {
    assert.ok(entry.reason.length > 40, `${entry.name}: reason too thin to review`)
    assert.ok(!targets.some((target) => target.name === entry.name), `${entry.name} is both rendered and held back`)
  }
})

test("destinations are unique and rooted in a known placeholder", () => {
  const destinations = targets.map((target) => target.destination)
  assert.equal(new Set(destinations).size, destinations.length, "two targets share a destination")
  for (const destination of destinations) {
    assert.match(destination, /^\{(home|tinshell)\}\//)
  }
})
