# Generated by house-palette from palette.json — do not edit by hand.
# Source revision fixture, sha256 a61d839291aa390dd3c17a6533632c660ba0cd580af1d64a7007e5562ef73ca0.
# Regenerate with bin/render --target zsh-colors; a hand edit fails bin/render --check.

# Terminal palette for the login shell. Source this file from the shell's own
# startup file; it exports LS_COLORS and touches nothing else.

LS_COLORS="di=#8ab5f7:ln=#4cccf2:pi=#b88cf2:so=#8af7ae:bd=#f0b35a:cd=#f0b35a:or=#606163:ex=#8af7ae:do=#b88cf2:su=#ff6b6b:sg=#ff6b6b:tw=#adcbf9:ow=#adcbf9:st=#adcbf9:mi=#ff6b6b:rs=#e6e6e6:fi=#e6e6e6:*.md=#c9c9c9:*.json=#f0b35a:*.toml=#f0b35a:*.yaml=#f0b35a:*.yml=#f0b35a:*.css=#4cccf2:*.ts=#8ab5f7:*.tsx=#8ab5f7:*.js=#f0b35a:*.sh=#8af7ae:*.lock=#606163"
export LS_COLORS
