/**
 * render.ts — turns the source into the files the renderer owns, and compares
 * what a render would write against what is on disk.
 *
 * `check` compares bytes, not timestamps: a generated file that was edited by
 * hand, or one the source moved past, differs from the render and fails. The
 * same comparison runs against the committed goldens, so the rendered bytes are
 * reviewed like any other source in this repository.
 */

import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { piThemeColours } from "./pi-theme.ts"
import { frozenValues, tokenMap, type Palette } from "./palette.ts"
import { targets, type Target } from "./targets.ts"

export const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)))

export type Roots = { home: string; tinshell: string }
export type SourceInfo = { path: string; revision: string; sha256: string }
export type RenderedFile = { target: string; destination: string; path: string; content: string }
export type Drift = { path: string; kind: "missing" | "stale" }

const PLACEHOLDER = /\{\{\s*([A-Za-z0-9._-]+)\s*\}\}/g

export function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex")
}

/** Source identity recorded in every header and in the manifest. */
export function readSource(relative = "palette.json"): SourceInfo {
  const path = join(repoRoot, relative)
  const text = readFileSync(path, "utf8")
  return { path: relative, revision: sourceRevision(), sha256: sha256(text) }
}

function sourceRevision(): string {
  // A fixture render pins this so the golden files do not move with the
  // repository's own history.
  const pinned = process.env.HOUSE_PALETTE_REVISION
  if (pinned !== undefined && pinned !== "") return pinned
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: repoRoot, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim()
  } catch {
    return "no-commit"
  }
}

/** The full token table a template may address: roles, composites, the ANSI slots, the glass surfaces and pi's roles. */
export function renderTokens(palette: Palette): Map<string, string> {
  const tokens = tokenMap(palette)
  const { colors, export: exported } = piThemeColours(palette)
  for (const [key, value] of Object.entries(colors)) tokens.set(`pi.${key}`, value)
  for (const [key, value] of Object.entries(exported)) tokens.set(`pi.export.${key}`, value)
  return tokens
}

export function expandTemplate(template: string, templateName: string, tokens: Map<string, string>): string {
  return template.replace(PLACEHOLDER, (_match, name: string) => {
    const value = tokens.get(name)
    if (value === undefined) throw new Error(`${templateName}: unresolved placeholder ${name}`)
    return value
  })
}

function headerLine(target: Target, source: SourceInfo): string {
  return [
    `Generated by house-palette from ${source.path} — do not edit by hand.`,
    `Source revision ${source.revision}, sha256 ${source.sha256}.`,
    `Regenerate with bin/render --target ${target.name}; a hand edit fails bin/render --check.`,
  ].join("\n")
}

export function headerFor(target: Target, source: SourceInfo): string {
  const body = headerLine(target, source)
  switch (target.header) {
    case "block":
      return `/* ${body.replaceAll("\n", "\n   ")} */\n\n`
    case "hash":
      return `${body
        .split("\n")
        .map((line) => `# ${line}`)
        .join("\n")}\n\n`
    case "dash":
      return `${body
        .split("\n")
        .map((line) => `-- ${line}`)
        .join("\n")}\n\n`
    case "none":
      return ""
  }
}

function resolveDestination(destination: string, roots: Roots): string {
  return destination.replace("{home}", roots.home).replace("{tinshell}", roots.tinshell)
}

export function renderTarget(palette: Palette, source: SourceInfo, tokens: Map<string, string>, target: Target, roots: Roots): RenderedFile {
  const templatePath = join(repoRoot, "templates", target.template)
  const template = readFileSync(templatePath, "utf8")
  const body = expandTemplate(template, target.template, tokens)
  return {
    target: target.name,
    destination: target.destination,
    path: resolveDestination(target.destination, roots),
    content: `${headerFor(target, source)}${body}`,
  }
}

/** Every selected target, plus the manifest that records what was written. */
export function renderAll(palette: Palette, source: SourceInfo, roots: Roots, names?: string[]): RenderedFile[] {
  const selected = names === undefined ? targets : targets.filter((target) => names.includes(target.name))
  if (names !== undefined) {
    const unknown = names.filter((name) => !targets.some((target) => target.name === name))
    if (unknown.length > 0) throw new Error(`unknown target: ${unknown.join(", ")}`)
  }
  const tokens = renderTokens(palette)
  const files = selected.map((target) => renderTarget(palette, source, tokens, target, roots))
  return [...files, manifestFile(palette, source, files, roots)]
}

function manifestFile(palette: Palette, source: SourceInfo, files: RenderedFile[], roots: Roots): RenderedFile {
  const entries = files
    .map((file) => [file.target, { destination: file.destination, sha256: sha256(file.content) }] as const)
    .sort(([a], [b]) => (a < b ? -1 : 1))
  const manifest = {
    version: 1,
    source,
    regenerate: "bin/render",
    targets: Object.fromEntries(entries),
    frozen: frozenValues(palette),
  }
  const destination = "{home}/.config/house-palette/manifest.json"
  return {
    target: "manifest",
    destination,
    path: join(roots.home, ".config", "house-palette", "manifest.json"),
    // The manifest records every other file's digest, so it is rendered last,
    // and no file records a digest of itself.
    content: `${JSON.stringify(manifest, null, 2)}\n`,
  }
}

export function checkFiles(files: RenderedFile[]): Drift[] {
  const drift: Drift[] = []
  for (const file of files) {
    if (!existsSync(file.path)) {
      drift.push({ path: file.path, kind: "missing" })
      continue
    }
    if (readFileSync(file.path, "utf8") !== file.content) drift.push({ path: file.path, kind: "stale" })
  }
  return drift
}

export function writeFiles(files: RenderedFile[]): void {
  for (const file of files) {
    mkdirSync(dirname(file.path), { recursive: true })
    writeFileSync(file.path, file.content)
  }
}
